name: Flutter Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'if:
      
      - run: flutter pub get

      - run: flutter analyze

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
